# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - backend

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'



steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: 'publish'
    # workingDirectory: backend
    # configuration: Release
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend'
    zipAfterPublish: true

# - task: ArchiveFiles@2
#   displayName: 'Create archive for app service deployment'
#   inputs:
#     rootFolderOrFile: '$(Build.DefaultWorkingDirectory)\backend\bin\Release'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.StagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-cloud-deployment'
    appType: 'webAppLinux'
    WebAppName: 'app-backend-myapp789'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|7.0'
