# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - backend

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: 'publish'
    arguments: '--configuration $(BuildConfiguration)'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-cloud-deployment'
    appType: 'webAppLinux'
    WebAppName: 'app-backend-myapp789'
    packageForLinux: '**/*.zip'
    RuntimeStack: 'DOTNETCORE|7.0'
